-- CreateEnum
CREATE TYPE "EventTheme" AS ENUM ('CONFERENCES', 'MUSIC_FESTIVAL', 'WORKSHOPS', 'WEDDINGS', 'SPORTS_EVENTS', 'MEETUPS');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "eventTheme" "EventTheme" NOT NULL DEFAULT 'CONFERENCES';
